== CPU仕様

=== 命令フォーマット

.即値形式(I形式)
[wavedrom, ,svg]
....
{reg: [
  {bits:  5, name: 'opcode'},
  {bits:  3, name: 'opcode_sub'},
  {bits:  5, name: 'rd'},
  {bits:  3, name: 'rs1'},
  {bits: 32, name: 'imm'},
], config: {hspace: 1024}}
....

.ストア形式(S形式)
[wavedrom, ,svg]
....
{reg: [
  {bits:  5, name: 'opcode'},
  {bits:  3, name: 'opcode_sub'},
  {bits:  5, name: 'rs2'},
  {bits:  3, name: 'rs1'},
  {bits: 32, name: 'imm'},
], config: {hspace: 1024}}
....

.レジスタ形式(R形式)
[wavedrom, ,svg]
....
{reg: [
  {bits:  5, name: 'opcode'},
  {bits:  3, name: 'opcode_sub'},
  {bits:  5, name: 'rd'},
  {bits:  5, name: 'rs1'},
  {bits:  5, name: 'rs2'},
  {bits: 25, name: 'reserved'},
], config: {hspace: 1024}}
....


=== 命令一覧

[options="header"]
|===
      | OpCode | OpCodeSub | Inst | Kind | Description
.1+^.^| 00000  | 000       | nop  | -    | 何もしない
.2+^.^| 00001  | 001       | add  | R    | 足し算
               | 010       | sub  | R    | 引き算
.2+^.^| 00010  | 001       | addi | I    | 足し算
               | 010       | subi | I    | 引き算
.4+^.^| 00011  | 000       | beq  | R    | branch if equal
               | 001       | bne  | R    | branch if not equal
               | 010       | blt  | R    | branch if less than (signed)
               | 011       | ble  | R    | branch if less than or equal (signed)
.5+^.^| 00100  | 000       |  lw  | I    | 32bit load
               | 001       |  lh  | I    | 16bit load(未実装)
               | 010       |  lb  | I    | 8bit load(未実装)
               | 011       | lhu  | I    | 16bit load unsigned(未実装)
               | 100       | lbu  | I    | 8bit load unsigned(未実装)
.3+^.^| 00101  | 000       |  sw  | S    | 32bit store
               | 001       |  sh  | S    | 16bit store(未実装)
               | 010       |  sb  | S    | 8bit store(未実装)
.4+^.^| xxxxx  | 000       | xxx  | x    | xxxx
               | xxx       | xxx  | x    | XXXX
               | xxx       | xxx  | x    | XXXX
               | xxx       | xxx  | x    | XXXX
|===



== 命令説明

=== 基本算術命令

==== 00001

* add(001) : レジスタ `rs1` と `rs2` の値を足しわせた結果をレジスタ `rd` に保存する ⇒ `rd = rs1 + rs2`

* sub(010) : レジスタ `rs1` から `rs2` の値を引いた結果をレジスタ `rd` に保存する ⇒ `rd = rs1 - rs2`

==== 00010

* addi(001) : レジスタ `rs1[2:0]` と 即値 `imm` の値を足しわせた結果をレジスタ `rd` に保存する ⇒ `rd = rs1 + imm`

* subi(010) : レジスタ `rs1[2:0]` から 即値 `imm` の値を引いた結果をレジスタ `rd` に保存する ⇒ `rd = rs1 - imm`

=== 分岐命令

==== 00011

* beq(000) : レジスタ `rs1` と `rs2` の値が等しい場合、現在の `pc` + 6 をレジスタ `rd` に書き込み、即値 `imm` だけ pc を進める ⇒ `if (rs1 == rs2) { rd = pc + 6; pc += sext(imm); }`
** sext(imm) : 即値 `imm` を符号拡張する
** 等しくなかった場合は何もせず次の命令へ進む

* bne(001) : レジスタ `rs1` と `rs2` の値が等しくない場合、現在の `pc` + 6 をレジスタ `rd` に書き込み、即値 `imm` だけ pc を進める ⇒ `if (rs1 != rs2) { rd = pc + 6; pc += sext(imm); }`

* blt(010) : レジスタ `rs1` の値が `rs2` の値未満（符号付き比較）の場合、現在の `pc` + 6 をレジスタ `rd` に書き込み、即値 `imm` だけ pc を進める ⇒ `if (rs1 < rs2) { rd = pc + 6; pc += sext(imm); }`

* ble(011) : レジスタ `rs1` の値が `rs2` の値以下（符号付き比較）の場合、現在の `pc` + 6 をレジスタ `rd` に書き込み、即値 `imm` だけ pc を進める ⇒ `if (rs1 <= rs2) { rd = pc + 6; pc += sext(imm); }`

=== メモリアクセス命令

==== 00100

* lw(000) : レジスタ `rs1` と 即値 `imm` の値を足しわせたアドレスから 32bit のデータを読み込み、レジスタ `rd` に保存する ⇒ `rd = mem[x[rs1] + imm]`

* lh(001) : レジスタ `rs1` と 即値 `imm` の値を足しわせたアドレスから 16bit のデータを読み込み、符号拡張してレジスタ `rd` に保存する ⇒ `rd = (signed)mem[x[rs1] + imm][15:0]`

* lb(010) : レジスタ `rs1` と 即値 `imm` の値を足しわせたアドレスから 8bit のデータを読み込み、符号拡張してレジスタ `rd` に保存する ⇒ `rd = (signed)mem[x[rs1] + imm][7:0]`

* lhu(011) : レジスタ `rs1` と 即値 `imm` の値を足しわせたアドレスから 16bit のデータを読み込み、ゼロ拡張してレジスタ `rd` に保存する ⇒ `rd = (unsigned)mem[x[rs1] + imm][15:0]`

* lbu(100) : レジスタ `rs1` と 即値 `imm` の値を足しわせたアドレスから 8bit のデータを読み込み、ゼロ拡張してレジスタ `rd` に保存する ⇒ `rd = (unsigned)mem[x[rs1] + imm][7:0]`

==== 00101

* sw(000) : レジスタ `rs1` と 即値 `imm` の値を足しわせたアドレスにレジスタ `rs2` の値を書き込む ⇒ `mem[x[rs1] + imm][31:0] = rs2`

* sh(001) : レジスタ `rs1` と 即値 `imm` の値を足しわせたアドレスにレジスタ `rs2` の値を書き込む ⇒ `mem[x[rs1] + imm][15:0] = rs2`

* sb(010) : レジスタ `rs1` と 即値 `imm` の値を足しわせたアドレスにレジスタ `rs2` の値を書き込む ⇒ `mem[x[rs1] + imm][7:0] = rs2`

== 用語説明

[options="header"]
|===
| yogo          | setsumei
| nop           | no operation の略。何もしない。
| opcode        | Operation Code の略。命令の識別番号。
| opcode_sub    | opcode による命令識別の補助。
| rd            | Register Destination の略。命令の結果を格納するレジスタのアドレスを指す。
| rs1, rs2      | Register Source の略。参照するレジスタのアドレスを指す。
| imm           | Immediate の略。即値。そのまま渡したい数値。
| reserved      | データの空き地。
| pc            | Program Counter の略。現在実行している命令のメモリのアドレス。
| yogo          | setsumei
| yogo          | setsumei
| yogo          | setsumei
|===
