== CPU仕様

=== 命令フォーマット

.即値形式
[wavedrom, ,svg]
....
{reg: [
  {bits:  5, name: 'opcode'},
  {bits:  3, name: 'opcode_sub'},
  {bits:  5, name: 'rd'},
  {bits:  3, name: 'rs1'},
  {bits: 32, name: 'imm'},
], config: {hspace: 1024}}
....

.レジスタ形式
[wavedrom, ,svg]
....
{reg: [
  {bits:  5, name: 'opcode'},
  {bits:  3, name: 'opcode_sub'},
  {bits:  5, name: 'rd'},
  {bits:  5, name: 'rs1'},
  {bits:  5, name: 'rs2'},
  {bits: 25, name: 'reserved'},
], config: {hspace: 1024}}
....


=== 命令一覧

[options="header"]
|===
      | OpCode | OpCodeSub | Inst | Kind | Description
.2+^.^| 00001  | 001       | add  | R    | 足し算
.2+^.^| 00010  | 001       | addi | I    | 足し算
               | xxx       | xxx  | x    | XXXX
|===



== 命令説明

=== 基本算術命令

==== 00001

* add(001) : レジスタ `rs1` と `rs2` の値を足しわせた結果をレジスタ `rd` に保存する ⇒ `rd = rs1 + rs2`

==== 00010

* addi(001) : レジスタ `rs1` と 即値 `imm` の値を足しわせた結果をレジスタ `rd` に保存する ⇒ `rd = rs1 + imm`

=== 分岐命令

==== 00011

* beq(000) : レジスタ `rs1` と `rs2` の値が等しい場合、現在の `pc` をレジスタ `rd` に書き込み、即値 `imm` だけ pc を進める ⇒ `if (rs1 == rs2) { rd = pc; pc += sext(imm); }`
** sext(imm) : 即値 `imm` を符号拡張する
** 等しくなかった場合は何もせず次の命令へ進む

* bne(001) : レジスタ `rs1` と `rs2` の値が等しくない場合、現在の `pc` をレジスタ `rd` に書き込み、即値 `imm` だけ pc を進める ⇒ `if (rs1 != rs2) { rd = pc; pc += sext(imm); }`

* blt(010) : レジスタ `rs1` の値が `rs2` の値より小さい場合、現在の `pc` をレジスタ `rd` に書き込み、即値 `imm` だけ pc を進める ⇒ `if (rs1 < rs2) { rd = pc; pc += sext(imm); }`

* ble(011) : レジスタ `rs1` の値が `rs2` の値以下の場合、現在の `pc` をレジスタ `rd` に書き込み、即値 `imm` だけ pc を進める ⇒ `if (rs1 <= rs2) { rd = pc; pc += sext(imm); }`

== 用語説明

[options="header"]
|===
| yogo          | setsumei
| opcode        | Operation Code の略。命令の識別番号。
| opcode_sub    | opcode による命令識別の補助。
| rd            | Register Destination の略。命令の結果を格納するレジスタのアドレスを指す。
| rs1, rs2      | Register Source の略。参照するレジスタのアドレスを指す。
| imm           | Immediate の略。即値。そのまま渡したい数値。
| reserved      | データの空き地。
| pc            | Program Counter の略。現在実行している命令のメモリのアドレス。
| yogo          | setsumei
| yogo          | setsumei
| yogo          | setsumei
|===
