== CPU仕様

:toc:

=== 命令フォーマット

.即値形式(I形式)
[wavedrom, ,svg]
....
{reg: [
  {bits:  5, name: 'opcode'},
  {bits:  3, name: 'opcode_sub'},
  {bits:  5, name: 'rd'},
  {bits:  3, name: 'rs1'},
  {bits: 32, name: 'imm'},
], config: {hspace: 1024}}
....

.ストア形式(S形式)
[wavedrom, ,svg]
....

{reg: [
  {bits:  5, name: 'opcode'},
  {bits:  3, name: 'opcode_sub'},
  {bits:  5, name: 'rs2'},
  {bits:  3, name: 'rs1'},
  {bits: 32, name: 'imm'},
], config: {hspace: 1024}}
....

.レジスタ形式(R形式)
[wavedrom, ,svg]
....
{reg: [
  {bits:  5, name: 'opcode'},
  {bits:  3, name: 'opcode_sub'},
  {bits:  5, name: 'rd'},
  {bits:  5, name: 'rs1'},
  {bits:  5, name: 'rs2'},
  {bits: 25, name: 'reserved'},
], config: {hspace: 1024}}
....

.分岐形式(B形式)
[wavedrom, ,svg]
....
{reg: [
  {bits:  5, name: 'opcode'},
  {bits:  3, name: 'opcode_sub'},
  {bits:  5, name: 'rd'},
  {bits:  5, name: 'rs1'},
  {bits:  5, name: 'rs2'},
  {bits: 25, name: 'imm'},
], config: {hspace: 1024}}
....

=== 命令一覧

[options="header"]
|===
      | OpCode | OpCodeSub | Inst | Kind | Description
.1+^.^| 00000  | 000       | nop  | -    | 何もしない
.2+^.^| 00001  | 001       | add  | R    | 足し算
               | 010       | sub  | R    | 引き算
.2+^.^| 00010  | 001       | addi | I    | 足し算
               | 010       | subi | I    | 引き算
.5+^.^| 00011  | 000       | beq  | B    | branch if equal
               | 001       | bne  | B    | branch if not equal
               | 010       | blt  | B    | branch if less than (signed)
               | 011       | ble  | B    | branch if less than or equal (signed)
               | 100       | jal  | I    | jump and link
.5+^.^| 00100  | 000       |  lw  | I    | 32bit load
               | 001       |  lh  | I    | 16bit load
               | 010       |  lb  | I    | 8bit load
               | 011       | lhu  | I    | 16bit load unsigned
               | 100       | lbu  | I    | 8bit load unsigned
.3+^.^| 00101  | 000       |  sw  | S    | 32bit store
               | 001       |  sh  | S    | 16bit store
               | 010       |  sb  | S    | 8bit store
.2+^.^| 00110  | 000       |  in  | I    | in
               | 001       | out  | S    | out
.3+^.^| 00111  | 000       | and  | R    | AND 演算
               | 001       | or   | R    | OR 演算
               | 010       | xor  | R    | XOR 演算
               | 011       | srl  | R    | 右論理シフト
               | 100       | sra  | R    | 右算術シフト
               | 101       | sll  | R    | 左論理シフト
.3+^.^| 01000  | 000       | andi | I    | AND 演算
               | 001       | ori  | I    | OR 演算
               | 010       | xori | I    | XOR 演算
               | 011       | srli | I    | 右論理シフト
               | 100       | srai | I    | 右算術シフト
               | 101       | slli | I    | 左論理シフト
|===

== 命令説明

=== 基本算術命令

==== 00001

* add(001) : レジスタ `r[rs1]` と `r[rs2]` の値を足しわせた結果をレジスタ `r[rd]` に保存する ⇒ `r[rd] = r[rs1] + r[rs2]`

* sub(010) : レジスタ `r[rs1]` から `r[rs2]` の値を引いた結果をレジスタ `r[rd]` に保存する ⇒ `r[rd] = r[rs1] - r[rs2]`

==== 00010

* addi(001) : レジスタ `r[rs1[2:0]]` と 即値 `imm` の値を足しわせた結果をレジスタ `r[rd]` に保存する ⇒ `r[rd] = r[rs1] + imm`

* subi(010) : レジスタ `r[rs1[2:0]]` から 即値 `imm` の値を引いた結果をレジスタ `r[rd]` に保存する ⇒ `r[rd] = r[rs1] - imm`

=== 分岐命令

==== 00011

* beq(000) : レジスタ `r[rs1]` と `r[rs2]` の値が等しい場合、現在の `pc` + 6 をレジスタ `r[rd]` に書き込み、即値 `imm` だけ pc を進める ⇒ `if (r[rs1] == r[rs2]) { r[rd] = pc + 6; pc += sext(imm); }`
** sext(imm) : 即値 `imm` を符号拡張する
** 等しくなかった場合は何もせず次の命令へ進む

* bne(001) : レジスタ `r[rs1]` と `r[rs2]` の値が等しくない場合、現在の `pc` + 6 をレジスタ `r[rd]` に書き込み、即値 `imm` だけ pc を進める ⇒ `if (r[rs1] != r[rs2]) { r[rd] = pc + 6; pc += sext(imm); }`

* blt(010) : レジスタ `r[rs1]` の値が `r[rs2]` の値未満（符号付き比較）の場合、現在の `pc` + 6 をレジスタ `r[rd]` に書き込み、即値 `imm` だけ pc を進める ⇒ `if (r[rs1] < r[rs2]) { r[rd] = pc + 6; pc += sext(imm); }`

* ble(011) : レジスタ `r[rs1]` の値が `r[rs2]` の値以下（符号付き比較）の場合、現在の `pc` + 6 をレジスタ `r[rd]` に書き込み、即値 `imm` だけ pc を進める ⇒ `if (r[rs1] <= r[rs2]) { r[rd] = pc + 6; pc += sext(imm); }`

* jal(100) : レジスタ `r[rs1[2:0]]` と 即値 `imm` の値を足し合わせたアドレスを `pc` に設定し、現在の `pc` + 6 をレジスタ `r[rd]` に書き込む ⇒ `r[rd] = pc + 6; pc = r[rs1] + imm;`

=== メモリアクセス命令

==== 00100

* lw(000) : レジスタ `r[rs1[2:0]]` と 即値 `imm` の値を足しわせたアドレスから 32bit のデータを読み込み、レジスタ `r[rd]` に保存する ⇒ `r[rd] = mem[r[rs1] + imm]`

* lh(001) : レジスタ `r[rs1[2:0]]` と 即値 `imm` の値を足しわせたアドレスから 16bit のデータを読み込み、符号拡張してレジスタ `r[rd]` に保存する ⇒ `r[rd] = (signed)mem[r[rs1] + imm][15:0]`

* lb(010) : レジスタ `r[rs1[2:0]]` と 即値 `imm` の値を足しわせたアドレスから 8bit のデータを読み込み、符号拡張してレジスタ `r[rd]` に保存する ⇒ `r[rd] = (signed)mem[r[rs1] + imm][7:0]`

* lhu(011) : レジスタ `r[rs1[2:0]]` と 即値 `imm` の値を足しわせたアドレスから 16bit のデータを読み込み、ゼロ拡張してレジスタ `r[rd]` に保存する ⇒ `r[rd] = (unsigned)mem[r[rs1] + imm][15:0]`

* lbu(100) : レジスタ `r[rs1[2:0]]` と 即値 `imm` の値を足しわせたアドレスから 8bit のデータを読み込み、ゼロ拡張してレジスタ `r[rd]` に保存する ⇒ `r[rd] = (unsigned)mem[r[rs1] + imm][7:0]`

==== 00101

* sw(000) : レジスタ `r[rs1[2:0]]` と 即値 `imm` の値を足しわせたアドレスにレジスタ `r[rs2]` の値を書き込む ⇒ `mem[r[rs1] + imm][31:0] = r[rs2]`

* sh(001) : レジスタ `r[rs1[2:0]]` と 即値 `imm` の値を足しわせたアドレスにレジスタ `r[rs2]` の値を書き込む ⇒ `mem[r[rs1] + imm][15:0] = r[rs2]`

* sb(010) : レジスタ `r[rs1[2:0]]` と 即値 `imm` の値を足しわせたアドレスにレジスタ `r[rs2]` の値を書き込む ⇒ `mem[r[rs1] + imm][7:0] = r[rs2]`

=== 入出力命令

==== 00110

* in(000) : レジスタ `r[rs1[2:0]]` と即値 `imm` の値を足し合わせた結果をデバイス ID とし，そのデバイスからデータをレジスタ `r[rd]` に読み込む ⇒ `r[rd] = in(r[rs1] + imm)`

* out(001) : レジスタ `r[rs1[2:0]]` と即値 `imm` の値を足し合わせた結果をデバイス ID とし，そのデバイスにレジスタ `r[rs2]` の値を書き込む ⇒ `out(r[rs1] + imm, r[rs2])`


== 用語定義

[options="header"]
|===
| 用語             | 定義
| nop              | no operation の略。何もしない。
| opcode           | Operation Code の略。命令の識別番号。
| opcode_sub       | opcode による命令識別の補助。
| rd               | Register Destination の略。命令の結果を格納するレジスタのアドレスを指す。
| rs1, rs2         | Register Source の略。参照するレジスタのアドレスを指す。
| imm              | Immediate の略。即値。そのまま渡したい数値。
| reserved         | データの空き地。
| pc               | Program Counter の略。現在実行している命令のメモリのアドレス。
| r[num]           | レジスタの num 番地。
| num[2:0]         | 数字 `num` から 2 〜 0bit 目を切り出した値。この場合、`num & 0b111` と同じ意味。
| デバイスID       | CPU に接続されている周辺機器(=デバイス)の識別番号(in/out命令でデバイスを指定して命令)
| UART             | 同期式シリアル通信を行う規格，UART(Universal Asynchronous Receiver Transmitter)
| クロックカウンタ | CPUと同じクロックを使ってカウントアップするカウンタ。クロック周波数を知っていれば時間を計測できる。
| yogo             | setsumei
|===


== デバイス

[options="header"]
|===
| デバイスID    | デバイスの種類
| 0x00000000    | UART
| 0x00000001    | SPI (Data)
| 0x00000002    | SPI (Mode)
| 0x00000003    | SPI (Clockshamt)
| 0x00000004    | GPIO(暫定All)
| 0x00001000    | クロックカウンタ[31:0]
| 0x00001001    | クロックカウンタ[63:32]
| 0x00001002    | 現在のクロック周波数
| 0x00001003    | リセット後からの経過時間（ミリ秒）[31:0]
| 0x00001004    | リセット後からの経過時間（ミリ秒）[63:32]
|===

* 存在しないデバイスIDを指定したとき
** 読み込みの場合、無効なデータ 0 を読み出す
** 書き込みの場合、何もしない

== タイマー

クロックカウンタは毎クロックカウントアップされ、オーバーフロー防止のため 64bit となっている。
クロックカウンタ / 現在のクロック周波数 で時間を計測することができる。

== SPI通信

=== mode0

- サンプリング : posedge
- シフト : negedge
- アイドル : LOW

[wavedrom, ,svg]
....
{signal: [
  {name: 'sclk',       wave: '0101010101|01010..'},
  {name: 'mosi',       wave: 'x.1.0.1.0.|..1....'},
  {name: 'miso',       wave: 'x.0.1.0.1.|..0....'},
  {name: 'misoBuf',    wave: 'x..0.1.0.1|...0...'},
  {name: '[sampling]', wave: '0..0.0.0.0|.0.0...'},
  {name: 'shiftReg',   wave: '3...3.3.3.|3.3.3..', data: ['10100101', '01001010', '10010101', '00101010', '01010110', '10101101', '01011010']},
  {name: '(slaveReg)', wave: '3...3.3.3.|3.3.3..', data: ['01011010', '10110101', '01101010', '11010101', '00101001', '01010010', '10100101']},
  {name: '[shifting]', wave: '0...0.0.0.|..0.0..'},
  {name: 'bitCounter', wave: '4...4.4.4.|4.4.4..', data: ['8', '7', '6', '5', '2', '1', '0']},
]}
....

== アセンブリ仕様

ここでは命令とデータの記述方法について説明する。

命令とデータは１つのファイル内にセクションを分けて記述する。
セクションは `===` で分割し、データセクション→命令セクションの順で記述する。

[source]
----
// データセクション

===

// 命令セクション
----

各セクションは空にすることも可能である。
各セクション毎の書き方については下の章で詳しく説明する。

[NOTE]
====

「命令」はCPUの動作を記述するもので、命令セクションに記述する。
「コマンド」はアセンブラに対する指令で、データセクションに記述する。

< メモリについて > +
メモリ上のアドレスを指定するために、ラベルを使用することが出来る。
命令メモリのアドレス空間とデータメモリのアドレス空間は分かれている。
命令メモリには命令ラベル、データメモリにはデータラベルを使用する。
====

=== 命令セクション

==== 命令記法

[options="header"]
|===
| 命令 | アセンブリ記述 | 備考
| 基本算術演算命令 | `add rd = rs1, rs2` | i32
| 基本算術演算命令 | `addi rd = rs1, imm` | imm は 命令ラベル・データラベル でも可。メモリの絶対値参照としても使う。u32
| 条件分岐命令 | `beq rd, (rs1, rs2) \-> imm` | imm は 命令ラベル でも可。
| 無条件分岐命令 | `jal rd, rs1[imm]` | immは符号付き
| メモリ読み込み・入力命令 (load, in) | `lb rd = rs1[i]` |
| メモリ書き込み・出力命令 (store, out) | `sb rs1[imm] = rs2` |
|===

==== 命令ラベル

`@` を先頭に付けることによって命令ラベルを定義する +
命令ラベルによって，特定の命令に対して別名を付けることが出来る +
(ex: 分岐命令によるジャンプ先として使用する)


[source]
----
< 記述例 >
@add3times
  addi r1, r2, 1
  addi r1, r2, 1
  addi r1, r2, 1
  jal rd = r3[0]
@main
  addi r1, r2, 1
  beq r3, (r2, r2) -> @add3times
----
[source]
----
< 概要 >
・基本構造

@「命令ラベル(string)」
  「命令記法に沿った命令a」
  「命令記法に沿った命令b」
　　　　　　　・
　　　　　　　・

・命令の後に@「命令ラベル」を続け、新たな命令を続けられる

@「命令ラベルa」
  「命令記法に沿った命令a」
  「命令記法に沿った命令b」
@「命令ラベルb」
  「命令記法に沿った命令c」
  「命令記法に沿った命令d」
　　　　　　　・
　　　　　　　・

・分岐命令など、命令ないで@「命令ラベル」を指定してジャンプ
@「命令ラベルa」
  「命令記法に沿った命令a」
  「命令記法に沿った命令b」
@「命令ラベルb」
  「命令記法に沿った命令c」
  　beq r3, (r2, r2) -> @「命令ラベルa」
　　　　　　　・
　　　　　　　・
----

==== データラベル

命令ラベルと同様に、データメモリのアドレスを指定するものとして、データラベルを呼び出すことが出来る +
(ex: 変数等のアドレス指定として使用する) +
宣言方法の詳細は後述
// <宣言方法>
// `$` を先頭に付けることによってデータラベルを定義する。
// データラベルによって，あるメモリ列に対して名前を付けることが出来る。

[source]
----
< 記述例 >
  $label
    byte4 0x20060630
  ===
    addi rd = rs1, $label
----
[source]
----
< 概要 >
・基本構造

$「データラベル(string)」
  「データコマンドに沿った命令a」
  「データコマンドに沿った命令b」
　　　　　　　・
　　　　　　　・

・データコマンドの後に$「データラベル」を続け、新たな命令を続けられる

@「データラベルa」
  「データコマンドに沿った命令a」
  「データコマンドに沿った命令b」
@「データラベルb」
  「データコマンドに沿った命令c」
  「データコマンドに沿った命令d」
　　　　　　　・
　　　　　　　・
----

=== データセクション

==== データコマンド記法
「データコマンド」は「アセンブリがデータメモリにデータを配置する仕方」を記述するための指令である。

char, string は UTF-8/Unicode で、アセンブリ側で数値にしてデータメモリ上に配置。
エンディアン は リトルエンディアン。
カンマ( , )区切りで連続してメモリ上に配置する。
命令長が6byteであることに注意。
[options="header"]
|===
| 命令 | アセンブリ記述 | 備考
| byte1 | byte1 0x41, ... |
| byte2 | byte2 0x1240, ... |
| byte4 | byte4 0x11020715, ...  |
| byte6 | byte6 0x080809, ...  | 
| char | char 'c', .... |
| string | string "shinrabansyo", ... | 末尾に1byteの0x00が付与される
|===

==== データラベル

`$` を先頭に付けることによってデータラベルを定義する。
データラベルによって，あるメモリ列に対して名前を付けることが出来る。
(ex: 変数等のアドレス指定として使用する) 

[source]
----
< 記述例 >
$label
  byte 0xde
  byte 0xad
  byte 0xbe
  byte 0xef
  byte 0x00
$nonsense
  byte 0xde
----

=== 呼び出し規約

==== 正引き

[options="header"]
|===
| レジスタ | 役割 | 保存する側 | 備考
| r0      | ゼロレジスタ | - | 常に0を保持する(書き込みは無効)
| r1      | リターンアドレス | 呼び出す側 |
| r2      | スタックポインタ | 呼ばれた側 | スタックフレームの先頭アドレスを保持
| r3      | フレームポインタ | 呼ばれた側 | スタックフレームの基準アドレス（= 関数フレームの先頭）を保持
| r4-r7   | 作業レジスタ1-4 | 呼び出す側 | 全ての命令形式で使用可能
| r8-r9   | 一時レジスタ1-2 | 呼び出す側 | I/S形式を使用する場合は作業レジスタへの移動が必要
| r10-r19 | 引数レジスタ1-10 / 戻り値レジスタ1-10 | 呼び出す側 |
| r20-r29 | 保存レジスタ1-10 | 呼ばれた側 |
| r30-r31 | 一時レジスタ3-4 | 呼び出す側 |
|===

==== 逆引き

[options="header"]
|===
| 役割 | レジスタ | 保存する側
| ゼロレジスタ         | r0 | -
| リターンアドレス     | r1 | 呼び出す側
| スタックポインタ     | r2 | 呼ばれた側
| フレームポインタ     | r3 | 呼ばれた側
| 作業レジスタ1-4      | r4-r7 | 呼び出す側
| 一時レジスタ1-2, 3-4 | r8-r9, r30-r31 | 呼び出す側
| 引数レジスタ1-10     | r10-r19 | 呼び出す側
| 戻り値レジスタ1-10   | r10-r19 | 呼び出す側
| 保存レジスタ1-10     | r20-r29 | 呼ばれた側
|===


==== 関数呼び出しの例

fpは基本的にfp(old)を指す。
スタックフレームはfpからの相対アドレスでアクセスする。
spはスタックフレームの先頭要素を指す。

===== 関数呼び出しの方法

[source]
----
@myfunc1
  // 引数設定
  addi r10 = r0, 0
  addi r11 = r0, 1
  ...
  addi r19 = r0, 9

  // 関数呼び出し
  addi r4 = r0, @myfunc2
  jal r1, r4[0]
----

===== プロローグ

高位アドレス
+----------+
| xxxxxxxx | <- fp(old)
+----------+
| xxxxxxxx |
+----------+
| fp(old)  | <- fp
+----------+
|    r20   |
+----------+
|    r21   |
+----------+
|    ...   |
+----------+
|    r29   | <- sp
+----------+
低位アドレス

[source]
----
@myfunc2
  // フレームポインタの退避
  add r2 = r2, -4
  sw r2[0] = r3
  addi r3 = r2, 0
  
  // 保存レジスタの退避
  addi r2 = r2, -40
  sw r3[-4] = r20    // 保存レジスタ 1 -> r3[ 1 * -4]
  sw r3[-8] = r21    // 保存レジスタ 2 -> r3[ 2 * -4]
  ...
  sw r3[-40] = r29   // 保存レジスタ10 -> r3[10 * -4]
----

===== エピローグ

[source]
----
  ...
  // 戻り値の設定
  addi r10 = r0, 0
  addi r11 = r0, 1
  ...
  addi r19 = r0, 9

  // 保存レジスタの復元
  lw r20 = r3[-4]
  lw r21 = r3[-8]
  ...
  lw r29 = r3[-40]
  addi r2 = r2, 40

  // フレームポインタの復元
  lw r3 = r3[0]
  addi r2 = r2, 4
  
  // return
  jal r0, r1[0]
----
